esphome:
  name: esp32w
  friendly_name: ESP32W

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0u8XdpKmzYZodJdT9fF1z1tCk9XToombgKzULPP7FhI="

ota:
  - platform: esphome
    password: "9cb7f620a7735c9765e72c40878049d9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.100
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32W Fallback Hotspot"
    password: "rYJ979MWzAyt"

globals:
  - id: encoder_value
    type: int
    initial_value: '0'
    restore_value: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21  # SW button
      mode: INPUT_PULLUP
      inverted: true
    name: "Encoder Button"
    on_press:
      - logger.log: "Button pressed"

sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: brightness_knob
    pin_a: GPIO4    # CLK pin
    pin_b: GPIO5    # DT pin
    min_value: 0
    max_value: 100
    resolution: 4    # Pulses per step: 1,2,4
    on_clockwise:
      then:
        - lambda: |-
            {
              id(encoder_value) = id(brightness_knob).state;
              id(encoder_value_script).execute();
            }
    on_anticlockwise:
      then:
        - lambda: |-
            {
              id(encoder_value) = id(brightness_knob).state;
              id(encoder_value_script).execute();
            }
    filters:
      - debounce: 25ms

script:
  - id: encoder_value_script
    then:
    - homeassistant.service:
        service: script.handle_encoder_value
        data:
          value: !lambda 'return id(encoder_value);'
    